fix(update): add config update liferay from 7.3 to 7.4
eclipse-sw360/sw360.website pull request #39
Opened 2023-06-15 05:00 UTC by tuannn2

- Update document for upgrade liferay from 7.3 to 7.4

2023-06-15 05:31 UTC, KoukiHama commented
Plan to review this on coming Monday.

2023-06-15 06:46 UTC, heliocastro requested changes

2023-06-15 06:46 UTC, heliocastro commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
> +  dir={LIFRAY_PATH_7.4}/tomcat-9.0.56
Typo: LIFRAY

2023-06-15 06:46 UTC, heliocastro commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
> +  jdbc.default.password={POSTGRE_PASSWORD}
Typo ? POSTGRE
Should not be POSTGRES ?

2023-06-15 06:46 UTC, heliocastro commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
>       ```
Move to python 3

2023-06-16 10:51 UTC, tuannn2 commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
>       ```
The migration scripts  are written in `python2` and depend on `python2-couchdb. 
 https://github.com/eclipse-sw360/sw360/blob/ec28fa1b4f032ef723b3fa7349cbed3d8bf79122/scripts/migrations/README.md?plain=1#LL5C132-L5C132

2023-06-16 17:29 UTC, ag4ums commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
>       ```
@tuannn2 the page is not updated, as we have those old python2 migration scripts, but as python2 is no more supported, all our migration scripts form rel 16 onwards are in python3

2023-06-19 02:54 UTC, tuannn2 commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
>       ```
Thanks for your comments, @heliocastro  @ag4ums. I updated.

2023-06-20 07:33 UTC, KoukiHama requested changes
> sql.data.com.liferay.portal.kernel.model.Country.country.id=21529
 
 Whether it in sw360.property is unnecessary or necessary, as it exists in the official main branch, it might be good to have some reference to it on upgrade documents.
 
 about re-import lars, please note whether user need to delete old file or not.

2023-06-20 07:33 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
> +* Set Environment for `${LIFERAY_INSTALL_7.4}`
can not use [.] here
So environment should be
LIFERAY_INSTALL_7_4

2023-06-20 07:33 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
> +  `$ export LIFERAY_INSTALL_7.4=/opt/liferay-ce-portal-7.4.3.18-ga18`
LIFERAY_INSTALL_7_4
other LIFERAY_INSTALL_7.4 also should be LIFERAY_INSTALL_7_4

2023-06-20 07:33 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
> +* After run command "mvn clean install -DskipTests" above, copy dependency in folder `/home/user/work16to17/sw360/deploy/jars` to  `${LIFERAY_INSTALL_7.4}/deploy`
Need to update here

https://github.com/eclipse-sw360/sw360.website/blob/07560370ba89a504bde6a3f81b9c4fd6c017ab16/content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md?plain=1#L115

2023-06-20 07:33 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
>  * We also suggest you change the environment settings (frontend/configuration/setenv.sh) to avoid the lack of memory before making and building SW360.
if user can reuse 7.3.4's setenv.sh,  please mention it.

https://github.com/eclipse-sw360/sw360.website/blob/07560370ba89a504bde6a3f81b9c4fd6c017ab16/content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md?plain=1#L119

2023-06-20 07:33 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
> +            $ python3 052_migrate_clearing_request_status.py
need to update 052 for python script.

Python 2.x code with Python 3.x. In Python 2, print is a statement and can be used without parentheses. However, in Python 3, print is a function and therefore always requires parentheses.

2023-06-20 07:33 UTC, KoukiHama commented on content/en/docs/Deployment/Upgrading/Upgrade_Version_SW360_16_To_17.md
> +            $ python3 053_remove_whitespace_component_name.py
before using this script,  "pip install panda" is required. 
 
 ーーーーーーーーーーーーーーー
 python3  053_remove_whitespace_component_name.py
Traceback (most recent call last):
  File "053_remove_whitespace_component_name.py", line 23, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

2023-06-20 08:33 UTC, KoukiHama approved these changes

2023-06-21 02:07 UTC, merged