Document to install and upgrade sw360 version 18.1.0
eclipse-sw360/sw360.website pull request #51
Opened 2024-02-02 08:44 UTC by hoangnt2

- Add document to native install 18.1.0 from scratch
- Add document to upgrade sw360 from 17.0.0 to 17.1.0

2024-02-12 15:23 UTC, heliocastro requested changes

2024-02-12 15:23 UTC, heliocastro commented on content/en/docs/Deployment/NativeInstall/Native-install-SW360-Version-18.1.0.md
> +##### 3.2.2 Install PostgreSQL
5 character instead of 2

2024-02-19 04:14 UTC, hoangnt2 commented on content/en/docs/Deployment/NativeInstall/Native-install-SW360-Version-18.1.0.md
> +##### 3.2.2 Install PostgreSQL
@heliocastro, This change is to unify the indentation of sub sections in 3.2, they should have 5 # character. Sorry but can you explain more about your comment?. I’m not sure I understand what you meant

2024-02-28 02:38 UTC, hoangnt2 commented
This PR is split into https://github.com/eclipse-sw360/sw360.website/pull/55 and https://github.com/eclipse-sw360/sw360.website/pull/54. I will close this PR

2024-02-28 02:38 UTC, closed without merging